from page_objects.TablePage import *


@allure.title('Check the ability to add record into the table')
def test_add_to_table(driver):
    table = Table(driver)
    table.open_page()
    table.open_registration_form()
    table.fill_first_name_field()
    table.fill_last_name_field()
    table.fill_email_field()
    table.fill_age_field()
    table.fill_salary_field()
    table.fill_department_field()
    table.assert_that_first_name_is_filled_correct()
    table.assert_that_last_name_is_filled_correct()
    table.assert_that_email_is_filled_correct()
    table.assert_that_age_is_filled_correct()
    table.assert_that_salary_is_filled_correct()
    table.assert_that_department_is_filled_correct()
    table.click_submit_button()
    table.assert_that_email_is_displayed_on_table()


@allure.title('Check the ability to save record without data')
def test_send_empty_registration_form(driver):
    table = Table(driver)
    table.open_page()
    table.open_registration_form()
    table.click_submit_button()
    table.assert_that_modal_is_displayed()


@allure.title('Check the ability to update record into the table')
def test_update_table(driver):
    table = Table(driver)
    table.open_page()
    table.open_registration_form()
    table.fill_first_name_field()
    table.fill_last_name_field()
    table.fill_email_field()
    table.fill_age_field()
    table.fill_salary_field()
    table.fill_department_field()
    table.assert_that_first_name_is_filled_correct()
    table.assert_that_last_name_is_filled_correct()
    table.assert_that_email_is_filled_correct()
    table.assert_that_age_is_filled_correct()
    table.assert_that_salary_is_filled_correct()
    table.assert_that_department_is_filled_correct()
    table.click_submit_button()
    table.assert_that_email_is_displayed_on_table()
    table.maximize_window()
    table.open_edit_mode()
    table.clear_first_name_field()
    table.clear_age_field()
    table.update_first_name_field()
    table.update_age_field()
    table.click_submit_button()
    table.assert_that_first_name_field_is_updated()
    table.assert_that_age_field_is_updated()
