from page_objects.Base import *
from page_objects.TextboxPage import *
from page_objects.CheckboxPage import *
from page_objects.RadioPage import *
from page_objects.ClickPage import *
from page_objects.ModalPage import *
from page_objects.SelectableListPage import *
from page_objects.SliderPage import *
from page_objects.TipsPage import *
from page_objects.AccordianPage import *
from page_objects.NestedFramePage import *
from page_objects.FramePage import *
from page_objects.AlertsPage import *
from page_objects.SelectMenuPage import *
from page_objects.TablePage import *
from page_objects.TipsPage import *